---
- name: Download and Unzip Artifact from Nexus
  hosts: local
  become: yes
  become_method: sudo
  tasks:
    - name: Ensure the destination directory exists
      file:
        path: /opt/nexus_artifact
        state: directory

    - name: Download the artifact from Nexus
      get_url:
        url: "http://192.168.0.42:8081/service/rest/v1/search/assets/download?sort=version&direction=desc&repository=maven-releases&format=maven2&group=com.murtuza&name=todo-web-app"
        dest: /opt/nexus_artifact/todo-web-app.zip

    - name: Find the downloaded zip file
      find:
        paths: /opt/nexus_artifact
        patterns: "todo-web-app*.zip"
      register: found_files

    - name: Set the zip file path variable
      set_fact:
        zip_file_path: "{{ found_files.files[0].path }}"

    - name: Ensure the unzipped directory exists
      file:
        path: /opt/nexus_artifact/todo-web-app
        state: directory

    - name: Unzip the downloaded artifact
      unarchive:
        src: "{{ zip_file_path }}"
        dest: /opt/nexus_artifact/todo-web-app
        remote_src: yes

    - name: Clean up the downloaded zip file
      file:
        path: "{{ zip_file_path }}"
        state: absent
